# Generated by Django 5.2 on 2025-08-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mehsul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
                ('kod', models.CharField(max_length=100)),
                ('kodlar', models.TextField(blank=True, null=True)),
                ('qiymet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.firma')),
            ],
        ),
    ]
