# Generated by Django 5.2 on 2025-08-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmalar'},
        ),
        migrations.AlterModelOptions(
            name='mehsul',
            options={'verbose_name': 'Mehsul', 'verbose_name_plural': 'Mehsullar'},
        ),
        migrations.AddField(
            model_name='mehsul',
            name='sekil',
            field=models.ImageField(blank=True, default='noimage.webp', null=True, upload_to='mehsul_sekilleri'),
        ),
    ]
