# Generated by Django 5.2 on 2025-08-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_firma_options_alter_mehsul_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='reklam_sekilleri')),
            ],
        ),
        migrations.AlterField(
            model_name='mehsul',
            name='sekil',
            field=models.ImageField(blank=True, default='mehsul_sekilleri/noimage.webp', null=True, upload_to='mehsul_sekilleri'),
        ),
    ]
